In [20]:
import pandas as pd
import numpy as np

# Q1 Pandas version

In [21]:
pd.__version__

'3.0.6'

In [22]:
df=pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

# Q2 Records count

In [23]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [24]:
len(df)

10000

# Q3. Fuel types

In [25]:
df['fuel_type'].nunique()

3

# Q4. Missing values

In [26]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

# Q5. Max fuel efficiency

In [27]:
df[df['origin']=='Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

# Q6. Median value of horsepower

In [28]:
median_before = df["horsepower"].median()
print("Median before filling:", median_before)

Median before filling: 254.0

In [29]:
most_frequent = df["horsepower"].mode()[0]
print("Most frequent value:", most_frequent)

Most frequent value: 252.0

In [32]:
df["horsepower"].fillna(most_frequent, inplace=True)

/tmp/ipykernel_23470/443359209.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["horsepower"].fillna(most_frequent, inplace=True)

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [33]:
median_after = df["horsepower"].median()
print("Median after filling:", median_after)

Median after filling: 254.0

# Q7. Sum of weights

In [34]:
cars_from_asia = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)
cars_from_asia

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [35]:
X = cars_from_asia.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [36]:
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [37]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [38]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [39]:
w = XTX_inv.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [40]:
result = w.sum()
print(result)

0.36919696904925486